### ISSUE TITLE
Export as Eagle-friendly ACCEL-ASCII

### ISSUE THREAD

**Issue by joshdotblack** [raphaelchang/battman-hardware#2]
Hi there!

I'm really enjoying following this project, the progress you've made over the past couple of weeks is crazy impressive, can't wait to see if the 4.0 PCBs work out!

Since your goal for this project is to be an hobbyist-friendly open-source BMS, could you possibly export the designs from Altium as ACCEL-ASCII or another Eagle compatible format? For better or worse, EagleCAD has become is the de facto standard for open source projects, so it'd be great if eagle-compatible files were available for people to take a look at and base their own designs off :)

**Comment by raphaelchang** [comment]
I've added a .PCB file in the project outputs folder, which should be usable by Eagle. I still haven't found a way to export the schematics.
